builds:
  # patchr:replace - main: ./cmd/{{ input "name" }}
  - main: ./cmd/go-cli-template
    # patchr:replace binary: {{ input "name" }}
    binary: go-cli-template
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
checksum:
  name_template: checksums.txt
archives:
  - format: binary
snapshot:
  name_template: master
changelog:
  sort: asc
  filters:
    exclude:
      - "Merge pull request"
      - "Merge branch"
release:
  github:
    owner: wreulicke
    # patchr:replace name: {{ input "name" }}
    name: go-cli-template
